name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ibm-plex
      - name: Build with Typst
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -v /usr/share/fonts:/fonts \
            -w /work \
            ghcr.io/typst/typst:latest \
            compile --font-path /fonts resume.typ
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
          retention-days: 90

  create_release:
    needs: build_typst_documents
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: resume
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          generate_release_notes: false